	const_def
	const pokecenternurse
	const difficultbookshelf
	const picturebookshelf
	const magazinebookshelf
	const teamrocketoath
	const incenseburner
	const merchandiseshelf
	const townmap
	const window
	const tv
	const homepage
	const radio1
	const radio2
	const trashcan
	const strengthboulder
	const smashrock
	const pokecentersign
	const martsign
	const goldenrodrockets
	const radiotowerrockets
	const elevatorbutton
	const daytotext
	const bugcontestresultswarp
	const bugcontestresults
	const initializeevents
	const asknumber1m
	const asknumber2m
	const registerednumberm
	const numberacceptedm
	const numberdeclinedm
	const phonefullm
	const rematchm
	const asknumber1f
	const asknumber2f
	const registerednumberf
	const numberacceptedf
	const numberdeclinedf
	const phonefullf
	const rematchf
	const gymstatue1
	const gymstatue2
	const receiveitem
	const receivetogepiegg
	const pcscript
	const gamecornercoinvendor
	const happinesschecknpc
